deploy_on_server_start: true
client: home
namespace: dev
worker:
  type: AsyncWorker
  task_queue: default
  workflows:
    - Task
    - TaskDispatcher
    - AwaitedTask
    - BatchTask
    - AwaitedBatchTask
  activities:
    - appfile
  max_workers: 100
