deploy_on_server_start: true
worker:  
  type: AsyncWorker
  client_address: "localhost:7233"
  task_queue: default
  workflows:
    - Task
    - TaskDispatcher
    - AwaitedTask
    - BatchTask
    - AwaitedBatchTask
  activities:
    - appfile
  max_workers: 100