name: hello_world
runner: WorkflowRunner
server: home
namespace: dev
overwritable: true
template: false
workflow:
  workflow: Task
  workflow_id: test3_workflow_id
  task_queue: default
  workflow_kwargs:
    activity: hello
    args:
      - world
    start_to_close_timeout:
      seconds: 5
    cancellation_type: ABANDON
    retry_policy:
      backoff_coefficient: 2.0
      initial_interval:
        seconds: 5
      maximum_attempts: 5
      non_retryable_error_types:
        - ValueError
        - KeyError

  retry_policy:
    backoff_coefficient: 2.0
    initial_interval:
      seconds: 5

    maximum_attempts: 5
    maximum_interval:
      seconds: 5

    non_retryable_error_types:
      - ValueError
      - KeyError
  memo:
    test: "this is a test"
