name: batch0
runner: WorkflowRunner
client_address: localhost:7233
workflow:
  workflow: BatchTask
  workflow_id: batch0_workflow_id
  task_queue: default
  workflow_kwargs:
    batch:
      - activity: hello
        args: 
          - BATHCH0_0_WORLD
        start_to_close_timeout:
          seconds: 5
        cancellation_type: ABANDON
        retry_policy:
          backoff_coefficient: 2.0
          initial_interval:
            seconds: 5
          maximum_attempts: 5
          non_retryable_error_types:
            - ValueError
            - KeyError

      - activity: hello
        args: 
          - BATHCH0_1_WORLD
        start_to_close_timeout:
          seconds: 5
        cancellation_type: ABANDON
        retry_policy:
          backoff_coefficient: 2.0
          initial_interval:
            seconds: 5
          maximum_attempts: 5
          non_retryable_error_types:
            - ValueError
            - KeyError

      - activity: hello
        args: 
          - BATHCH0_2_WORLD
        start_to_close_timeout:
          seconds: 5
        cancellation_type: ABANDON
        retry_policy:
          backoff_coefficient: 2.0
          initial_interval:
            seconds: 5
          maximum_attempts: 5
          non_retryable_error_types:
            - ValueError
            - KeyError
  
  retry_policy:
    backoff_coefficient: 2.0 
    initial_interval: 
      seconds: 5

    maximum_attempts: 5
    maximum_interval:
      seconds: 5

    non_retryable_error_types:
      - ValueError
      - KeyError
  memo: 
    test: "this is a test"