# -- WORKFLOW RUNNER TEST + TASK CHAINWORKFLOW
name: chain1
runner: WorkflowRunner
server: home
namespace: dev
workflow:
  workflow: Task
  workflow_id: chained_task_1
  task_queue: default
  workflow_kwargs:
    activity: appfile
    args:
      - CHAINED_ROMAIN_1

    at_end:
      chain_with:
        - handle:
            workflow: AwaitedTask
            workflow_id: awaited_task_id
          signal:
            signal: start
            signal_args:
        - handle:
            workflow: TaskDispatcher
            workflow_id: dispatcher
          signal:
            signal: queue
            signal_args:
              - "./deployments/test3.yaml"

    start_to_close_timeout:
      seconds: 5
    cancellation_type: ABANDON
    retry_policy:
      backoff_coefficient: 2.0
      initial_interval:
        seconds: 5
      maximum_attempts: 5
      non_retryable_error_types:
        - ValueError
        - KeyError

  retry_policy:
    backoff_coefficient: 2.0
    initial_interval:
      seconds: 5

    maximum_attempts: 5
    maximum_interval:
      seconds: 5

    non_retryable_error_types:
      - ValueError
      - KeyError
  memo:
    test: "this is a test"
