# -- WORKFLOW RUNNER TEST + TASK CHAINWORKFLOW
name: chain0
runner: WorkflowRunner
client_address: localhost:7233
workflow:
  workflow: Task
  workflow_id: chained_task_0
  task_queue: default
  workflow_kwargs:
    activity: hello
    args: 
      - CHAINED_WORLD_0

    at_end:
      chain_with:
        - handle:
            workflow: TaskDispatcher
            workflow_id: dispatcher
          signal:
            signal: queue
            signal_args: 
              - "./deployments/test3.yaml"

    start_to_close_timeout:
      seconds: 5
    cancellation_type: ABANDON
    retry_policy:
      backoff_coefficient: 2.0
      initial_interval:
        seconds: 5
      maximum_attempts: 5
      non_retryable_error_types:
        - ValueError
        - KeyError
  
  retry_policy:
    backoff_coefficient: 2.0 
    initial_interval: 
      seconds: 5

    maximum_attempts: 5
    maximum_interval:
      seconds: 5

    non_retryable_error_types:
      - ValueError
      - KeyError
  memo: 
    test: "this is a test"