name: dispatcher
runner: WorkflowRunner
server: home
namespace: dev
deploy_on_server_start: True
workflow:
  workflow: TaskDispatcher
  workflow_id: dispatcher
  task_queue: default
  workflow_kwargs:
    cancellation_type: WAIT_CANCELLATION_COMPLETED
    parent_close_policy: TERMINATE
    versioning_intent:
