# -- WORKFLOW RUNNER WITH TEMPWORKER TEST + TASK WORKFLOW
name: test5
runner: ScheduledWorkflowRunner
client_address: localhost:7233
workflow:
  workflow: Task
  workflow_id: test5_scheduled_workflow_id
  task_queue: default
  workflow_kwargs:
    activity: hello
    args: 
      - SCHEDULED_WORLD
    start_to_close_timeout:
      seconds: 5
    cancellation_type: ABANDON
    retry_policy:
      backoff_coefficient: 2.0
      initial_interval:
        seconds: 5
      maximum_attempts: 5
      non_retryable_error_types:
        - ValueError
        - KeyError

  scheduler_id: test5_scheduler_id
  intervals:
    - every:
        seconds: 10

  retry_policy:
    backoff_coefficient: 2.0 
    initial_interval: 
      seconds: 5
    maximum_attempts: 5
    maximum_interval:
      seconds: 5
    non_retryable_error_types:
      - ValueError
      - KeyError
  memo: 
    test: "this is a test"