app:
  env: development
  sanic:


  watcher:
    modules:
      workers:
        - ./workers
      # workflows:
      deployments:
        - ./deployments
      activities:
        - ./activities
      # runners:
    polling:
      on_server_start: True
      polling_interval: 10

  # temporalio:





  logging:
    version: 1
    disable_existing_loggers: False
    formatters:
      simple: 
        class: logging.Formatter
        format: "[%(asctime)s][%(name)s][%(process)d][%(levelname)s] | %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
    handlers:
      stream:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

      error_stream:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stderr

      error_file:
        class: logging.FileHandler
        level: ERROR
        formatter: simple
        filename: ./volume/errors.log

      access_file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: ./volume/log.log

    loggers:
      endpointAccess:
        level: INFO
        handlers: [stream, error_stream, error_file, access_file]
        propagate: False




# workers:
#   - type: AsyncWorker
#     client_address: "localhost:7233"
#     task_queue: default
#     workflows:
#       - Task
#     activities:
#       - test
#     max_workers: 100
    