app:
  env: development
  sanic:
    app:
      secret: xxxxxxx

  temporalio:
    default_server: home
    servers:
      - name: home
        ip: localhost
        port: 7233
        gui_port: 8233
        namespaces:
          # default namespace exist by default
          - name: dev
            retention: 2629743 #1month
          - name: prod
            retention: 2629743 # 1month
        default_namespace: dev

  watcher:
    modules:
      workers:
        basepaths:
          - ./deployments/workers
      workflows:
        basepaths:
          - ./{{ name }}/temporal/workflows.py
      deployments:
        basepaths:
          - ./deployments/tasks
      activities:
        basepaths:
          - ./{{ name }}/temporal/activities.py
      runners:
        basepaths:
          - ./{{ name }}/temporal/runners.py
    polling:
      on_server_start: True
      automatic_refresh: True
      polling_interval: 600

  authenticator:
    db: ":memory:"
    base_users:
      - username: test
        password: test
        auth_level:
          - "user"
          - "super user"
        max_age: 600

  logging:
    version: 1
    disable_existing_loggers: False
    formatters:
      simple:
        class: logging.Formatter
        format: "[%(asctime)s][%(name)s][%(process)d][%(levelname)s] | %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
    handlers:
      stream:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

      error_file:
        class: logging.FileHandler
        level: ERROR
        formatter: simple
        filename: ./volume/errors.log

      access_file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: ./volume/log.log

    loggers:
      endpointAccess:
        level: INFO
        handlers: [stream, error_file, access_file]
        propagate: False
      watcher:
        level: INFO
        handlers: [stream, error_file, access_file]
        propagate: False
      workflows:
        level: INFO
        handlers: [stream, error_file, access_file]
        propagate: False
      workers:
        level: INFO
        handlers: [stream, error_file, access_file]
        propagate: False
      temporal:
        level: INFO
        handlers: [stream, error_file, access_file]
        propagate: False
